// <auto-generated />
namespace hotelmanagementsystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixRooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixRooms));
        
        string IMigrationMetadata.Id
        {
            get { return "202506102225380_FixRooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
